//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACDemo2
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class UserInfo
    {
        [Key, Column(Order = 1)]
        [Display(Name = "Username: ")]
        public string username { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [StringLength(255, MinimumLength = 8)]
        [Display(Name = "Password: ")]
        public string passwordHash { get; set; }

        [Required]
        [Display(Name = "First Name: ")]
        public string firstName { get; set; }
        [Display(Name = "Middle Name: ")]
        public string middleName { get; set; }
        [Required]
        [Display(Name = "Last Name: ")]
        public string lastName { get; set; }

        [Required]
        [Key, Column(Order = 2)]
        [RegularExpression(@"^([\w\.\-]+)@([\w\-]+)((\.(\w){2,3})+)$", ErrorMessage = "Invalid E-mail ID")]
        [StringLength(150)]
        [Display(Name = "Email Address: ")]
        public string emailId { get; set; }

        [Display(Name = "Phone Number: ")]
        [RegularExpression(@"\d{3}-\d{3}-\d{4}", ErrorMessage = "Invalid Phone Number! Use Format XXX-XXX-XXXX")]
        public string phone { get; set; }
    }
}
